export const LOAD_CONTACT_REQUEST = "LOAD_CONTACT_REQUEST";
export const LOAD_CONTACT_SUCCESS = "LOAD_CONTACT_SUCCESS";
export const LOAD_CONTACT_FAIL = "LOAD_CONTACT_FAIL";
export const ADD_TO_CONTACTS = "ADD_TO_CONTACTS";
export const REMOVE_FROM_CONTACTS = "REMOVE_FROM_CONTACTS";

export const LOAD_CONTACT_CLASSES_REQUEST = "LOAD_CONTACT_CLASSES_REQUEST";
export const LOAD_CONTACT_CLASSES_SUCCESS = "LOAD_CONTACT_CLASSES_SUCCESS";
export const LOAD_CONTACT_CLASSES_FAIL = "LOAD_CONTACT_CLASSES_FAIL";
