export const LOAD_CONTENT_REQUEST = "LOAD_CONTENT_REQUEST";
export const LOAD_CONTENT_SUCCESS = "LOAD_CONTENT_SUCCESS";
export const LOAD_CONTENT_FAIL = "LOAD_CONTENT_FAIL";
export const RESET_CONTENT = "RESET_CONTENT";
