export const LOAD_EMERGENCY_REQUEST = "LOAD_EMERGENCY_REQUEST";
export const LOAD_EMERGENCY_SUCCESS = "LOAD_EMERGENCY_SUCCESS";
export const LOAD_EMERGENCY_FAIL = "LOAD_EMERGENCY_FAIL";
export const ADD_TO_EMERGENCY = "ADD_TO_EMERGENCY";
export const REMOVE_FROM_EMERGENCY = "REMOVE_FROM_EMERGENCY";
