export const LOAD_MAPS_REQUEST = "LOAD_MAPS_REQUEST";
export const LOAD_MAPS_SUCCESS = "LOAD_MAPS_SUCCESS";
export const LOAD_MAPS_FAIL = "LOAD_MAPS_FAIL";

export const ADD_MAPS_REQUEST = "ADD_MAPS_REQUEST";
export const ADD_MAPS_SUCCESS = "ADD_MAPS_SUCCESS";
export const ADD_MAPS_FAIL = "ADD_MAPS_FAIL";
