export const BLACK_BACKGROUND = "BLACK_BACKGROUND";
export const LIGHT_BACKGROUND = "LIGHT_BACKGROUND";

export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";
export const CHANGE_NAVBAR = "CHANGE_NAVBAR";
